spring:
  datasource:
    url: jdbc:mysql://localhost:3306/storage
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: letmein
  jpa:
    show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
cloud:
  aws:
    region:
      static: eu-central-1

application:
  bucket:
    name: file-storage-bkt